### ISSUE TITLE
홈 화면 마크업

### ISSUE THREAD

**Issue by songmilee** [ClimbFight/climbfighting-mobile#8]
## 이슈 내용
홈 화면 마크업을 진행합니다.

## 체크리스트

- [x] 로그인 직후의 홈 화면 
  - [x] 탭 네비게이션
  - [x] 날씨 정보 표시
  - [x] 등산 일기 리스트
![climb_home](https://user-images.githubusercontent.com/9676685/110908315-f7540380-8351-11eb-82b0-646e2f749f59.png)

## 참조자
@yujeongJeon

**Comment by yujeongJeon** [comment]
완료하여 이슈를 닫습니다.
